// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://foodex_app_user:CT7NeuOkhzWPuPx24AUHIQS0tth82InI@dpg-d84slcojs32c73a2jrvg-a.virginia-postgres.render.com/foodex_app?sslmode=require",
  },
});
